name : Cache node and npm dependencies
description : This action allows to cache node and npm dependencies based on package-lock.json file

input : 
  node-version : 
    description : 'Node.js version to setup'
    required : false
    default : '20.x'
  working-dir : 
    description : 'Working directory to run commands'
    required : false
    default : .

runs:
  using : composite
  steps :
    - name : Setup Node.js version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with :  
        node-version : ${{ inputs.node-version }}
    - name : Cache dependencies
      id  : cache
      uses : actions/cache@v3
      with :
        path : ${{ inputs.working-dir }}/node_modules
        key : deps-node-modules-${{ hashFiles(' ${{ inputs.working-dir }}/package-lock.json') }}
    - name : Install dependencies
      if : steps.cache.outputs.cache-hit != 'true' 
      run : npm ci
      shell : bash
      working-directory :  ${{ inputs.working-dir }}


