name : 16 -  2 - Working with Environments - Split into multiple jobs

on :
    workflow_dispatch :

jobs:
    deploy-test:
        name : Deploy to Test environment
        runs-on : ubuntu-latest
        environment : test
        steps:
           - name : Print environment
             run  : 
                  |
                   echo "Deploying to environment: test"
    e2e-test : 
        name : E2E Test environment
        runs-on : ubuntu-latest
        needs: deploy-test
        steps:
           - name : Print environment
             run  : 
                  |
                   echo "Run e2e tests in environment"
    deploy-prod-frontend:
        name : Deploy Frontend to Prod environment
        needs: e2e-test
        runs-on : ubuntu-latest
        environment : prod
        steps:
           - name : Print environment
             run  : 
                  |
                   echo "Deploying Frontend : production"
    deploy-prod-backend:
        name : Deploy Backend to Prod environment
        needs: e2e-test
        runs-on : ubuntu-latest
        environment : prod
        steps:
           - name : Print environment
             run  : 
                  |
                   echo "Deploying Backend : production"        